# Generated by Django 5.0.6 on 2024-07-09 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Order"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Product"},
        ),
    ]
